title = "Configuration file v1.0 for: RIS-enabled High Resolution Radar"

[owner]
name = "Martin Voigt Vejling"
mail = "martin.vejling@gmail.com"
mail_es = "mvv@es.aau.dk"
mail_math = "mvv@math.aau.dk"

["track changes"]
Python = "RIS-enabled High Resolution Radar v.1.0 - 20.09.2023:\n- Update with user specifications v.1.1 - 19.11.2023\n- Update to updated signal model v.1.2 - 04.12.2023\n- Update to estimation methods v.1.3 - 08.03.2024\n- Include OMP options v.1.4 - 10.06.2024\n"

[settings]
fc = 15000000000.0                      # float - Carrier frequency in Hz
p_tot_tx_dbm = 68                       # float - Total transmission power in dBm
p_noise_hz_dbm = -166                   # float - Noise power per Hz in dBm
sR = [ 3.0, 5.0, 6.0, 0.0, 0.0, 0.0,]
nR = [ 0, 0, 1,]
sU = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
NU = [ 2, 2,]
NR = [ 35, 35,]
delta_f = 120000.0                      # float - Subcarrier spacing in Hz
N = 75                                  # int - Number of subcarriers
c = 299792458                           # int - Speed of light
T1 = 50                                 # int - Number of channel uses in the prior step
T2 = 50                                 # int - Number of channel uses for high-resolution sensing
fading = "random_phase"                 # str - The type of fading, options: "random_phase", "rayleigh", "rayleigh_mean"
rcs_model = "rayleigh_mean"             # str - The type of radar cross section simulation, options: "rayleigh", "rayleigh_mean"
seed = 18

[positions]
Phi_taus = [ 60.0, 60.0, 60.0]
Phi_azs = [ 0.7, 0.8, 0.6]
Phi_els = [ 0.8, 0.7, 0.9]
Phi_rcs = [ 50.0, 5.0, 0.5]

[estimation]
method = "joint"                        # str - The method, options: "joint"
order_test = "OMP"                      # str - The method of estimation, options: "joint_eigenvalue_test", "eigenvalue_test", "OMP", "generalized_likelihood_ratio_test"
algPrior = "OMP"                # str - The method of estimation, options: "beamforming", "OMP"
algN = "OMP"                    # str - The method of estimation, options: "beamforming", "OMP"
algR = "OMP"                            # str - The method of estimation, options: "beamforming", "OMP"
beamformer = "MUSIC"                    # str - The pseudo-spectrum algorithm, options: "MUSIC", "CAPON", "BARTLETT"
optimization = "grid"                   # str - The optimization over the pseudo-spectrum, options: "grid", "optimize"
simulate_prior = true                   # str - If True run prior sensing step, else used specified prior by bounds input
cutoff_threshold = -0.25                 # float - The ref parameter used in the prior sensing step to find bounds of resolution region
res_scale = 15                          # float - Setting the resolution scale used for pseudo-spectrum grid in the prior step
confidence_level = 0.00001              # float - The confidence level used for estimating the number of targets with the spectral likelihood ratio test statistic
sparsity = 4                            # int - The maximum number of targets when using OMP
residual_thresholdN = 0.00003           # float - The residual norm threshold used to stop the OMP algorithm
residual_thresholdR = 0.000035          # float - The residual norm threshold used to stop the OMP algorithm
simPhi = "rcs"                          # str - How to simulate the point configuration, options: "None", "poisson", "binomial", "matern", "rcs"
intensity = 3                           # int - The number/expected number of targets
interaction_radius = 0.00000015         # float - The interaction radius used in matern simulation
LsxN = 2
LsyN = 2
LsfN = 45
LsfR = 2
K_delayN = 25
K_azN = 31
K_elN = 31
stdsN = 3.0
kernelN = [5, 5, 5]
K_delayR = 30
K_azR = 30
K_elR = 30
stdsR = 0.1
kernelR = [1, 8, 8]
